spring.application.name=fitness-nutrition-plan

jwt.secret=3209392ccaef0e1e7690daf6a6c35351c8542cdd2d2e24f9f144b7e533650472
jwt.expiration=86400000
jwt.refresh-expiration=604800000

spring.datasource.url=jdbc:mysql://localhost:3306/fitness_nutrition_db?useSSL=false&serverTimezone=Europe/Athens&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
